version: '2'
services:
    fr-app:
        image: fr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fr-mysql:3306/fr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fr-mysql:
        extends:
            file: mysql.yml
            service: fr-mysql
